# Generated by Django 5.0.7 on 2024-07-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("Fundamental", "Ensino fundamental"),
                            ("Medio", "Ensino médio"),
                            ("Tecnologo", "Tecnólogo"),
                            ("Superior", "Ensino Superior"),
                            ("Pos", "Pós"),
                            ("MBA", "MBA"),
                            ("Mestrado", "Mestrado"),
                            ("Doutorado", "Doutorado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Estudando", "Estudando"),
                            ("Concluido", "Concluído"),
                            ("Trancado", "Trancado"),
                            ("Interrompido", "Interrompido"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "salary_expectation",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("additional_info", models.TextField()),
            ],
        ),
    ]
