# Generated by Django 5.0.7 on 2024-07-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_application"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_company",
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("candidate", "Candidate"), ("company", "Company")],
                default="candidate",
                max_length=10,
            ),
        ),
    ]
